image: "rust:latest"

# Debian buster is the OS on this CoreOS instance as at 2020-10-22 but that has GStreamer 1.14.4
# whereas Me TV 3.1.x needs GStreamer 1.16.x as minimum. Hence the installation of GStreamer
# from Slomo's collection rather than packaging.

before_script:
  - uname -a
  - curl -L https://people.freedesktop.org/~slomo/gstreamer-1.16.1.tar.xz | tar -x --xz
  - sed -i "s;prefix=/root/gstreamer;prefix=$PWD/gstreamer;g" $PWD/gstreamer/lib/x86_64-linux-gnu/pkgconfig/*.pc
  - export PKG_CONFIG_PATH=$PWD/gstreamer/lib/x86_64-linux-gnu/pkgconfig
  - export LD_LIBRARY_PATH=$PWD/gstreamer/lib/x86_64-linux-gnu
  - export GST_PLUGIN_SYSTEM_PATH=$PWD/gstreamer/lib/x86_64-linux-gnu/gstreamer-1.0
  - export PATH=$PATH:$PWD/gstreamer/bin
  - export RUST_BACKTRACE=1
  - apt-get update -yq
  - apt-get install -y libgtk-3-dev libgstreamer1.0-dev xvfb  # libgstreamer-plugins-bad1.0-dev

test:cargo:
  script:
  - rustc --version
  - cargo --version
  - cargo update
  - cargo build
  - xvfb-run cargo test
  - cargo build --release
