image: "rust:latest"

before_script:
  - uname -a
  - curl -L https://people.freedesktop.org/~slomo/gstreamer-1.16.1.tar.xz | tar -x --xz
  - sed -i "s;prefix=/root/gstreamer;prefix=$PWD/gstreamer;g" $PWD/gstreamer/lib/x86_64-linux-gnu/pkgconfig/*.pc
  - export PKG_CONFIG_PATH=$PWD/gstreamer/lib/x86_64-linux-gnu/pkgconfig
  - export LD_LIBRARY_PATH=$PWD/gstreamer/lib/x86_64-linux-gnu
  - export GST_PLUGIN_SYSTEM_PATH=$PWD/gstreamer/lib/x86_64-linux-gnu/gstreamer-1.0
  - export PATH=$PATH:$PWD/gstreamer/bin
  - export RUST_BACKTRACE=1
  - apt-get update -yq
  - apt-get install -y libgtk-3-dev xvfb
#  - apt-get install -y libgstreamer-plugins-bad1.0-dev

test:cargo:
  script:
  - rustc --version && cargo --version
  - cargo build --verbose
  - xvfb-run cargo test --verbose
  - cargo build --verbose --release
