.TH "Me TV" 1 "2020-11-13" "3.1.0" "User Commands"
.SH NAME
me-tv \- a digital television (DVB) viewer for GTK and GStreamer.
.SH SYNOPSIS
.B me-tv
[\fI\,OPTION\/\fR]
.SH DESCRIPTION
.PP
Me TV is a GTK and GStreamer desktop application for watching digital television services that
use the DVBv5 standard (cf. DVB Website https://dvb.org/). Me TV works with DVB-T, DVB-T2,
DVB-C, DVB-S, DVB-S2, ISDB-T, ATSC, and DTMB devices that have kernel driver support.
.PP
The options are from:
.TP
\fB\-h\fR, \fB\-\-help\fR
display this help and exit.
.TP
\fB\-\-no\-gl\fR
do not try to use OpenGL.
.TP
\fB\-V\fR, \fB\-\-version\fR
output version information and exit.
.PP
When executing Me TV reads the Electronic Program Guide (EPG) data that is transmitted over the
air to populate a built-in program guide which can be used for scheduling recordings.
.PP
Me TV requires prior construction of a channels file for the local transmitter in
$HOME/.config/gstreamer-1.0/dvb-channels.conf. dvbv5-scan can produce such a file.
.PP
Me TV was initially created by Michael Lamothe (2007–2011) as a C/C++ program.  Russel Winder
then evolved the C/C++ code for a while before reimplementing in Rust for this version 3.
.SH AUTHOR
Russel Winder (2017–to date) <russel@winder.org.uk>
.SH COPYRIGHT
Copyright © 2017–2020  Russel Winder <russel@winder.org.uk>
